### PR TITLE
Convenience functions for streaming to files, fixes #148

### LINKED ISSUE #148: Inconvenient multi_add API
I'm using curl multi to download data from google BigQuery, downloading "pages" of data in parallel. I want to process the json by hand (in C++, for performance), so I want to just save each page to disk in a separate file. To that end, I'm supplying an open connection to `data`. That's a bit painful because if the user accidentally provides a bad combination of parameters, I might have to create 100,000 connections up front - that exhausts all open connections, and makes R + RStudio give weird/uninformative errors. Would it be possible `data` to also take a simple file name, and to open the connection on demand?

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
TBH I am a little worried about leaving the file open, because of the connection limit, especially in package code, where you cannot make assumptions about the number of open connections.

Could we come up with some  auto-close mechanism, that would close & reopen the files, as needed? This is starting to get difficult,  though.... I am not sure if it is worth it.

**Comment by jeroen** [comment]
Where are you worried to leave the file open? I think we auto-close anywhere we auto-open?

**Comment by jeroen** [comment]
Also by default if the user sets `data` to a string (filepath) we do not use R connections but the internal `file_writer()` type.

**Comment by gaborcsardi** [comment]
Oh, OK, all right then. I thought it uses  R connections.

**Comment by jeroen** [comment]
No, I used an internal wrapper around `FILE *` and `fwrite()` that is lazily opens the file on the first write, and closes it either explicitly or otherwise by the GC in the finalizer. Have a look at the code and manual for `?file_writer`.

**Comment by hadley** [comment]
Sweet, thanks!

**Pull request merged**
