### PR TITLE
possible webmockr integration

### PR DESCRIPTION
**Pull request by sckott**
@jeroen opening this to start a discussion to see if you'd be willing to incorporate changes for `webmockr` - if so, if you have any thoughts on the changes I've made. 

A few people have requested `curl` integration for `webmockr`, suggesting there's more than that that would use it.

I want an even smaller change (few lines of code) to `curl` than I've made in this PR - perhaps you can advise on how. 

The only thing changed right now in my fork of `curl` is `curl_fetch_memory()`: I first check if `webmockr` is installed, if not move on. If installed, then check if webmocking for curl is enabled; if so then proceed to call `webmockr::curl_mock_req`: https://github.com/ropensci/webmockr/blob/adapter-curl/R/curl_mocking.R

example:

```r
remotes::install_github("sckott/curl@mocking-minimal-footprint")
remotes::install_github("ropensci/webmockr@adapter-curl")
```

```r
library(curl)
library(webmockr)

# before mocking turned on
h <- new_handle()
curl_fetch_memory("https://httpbin.org/get?foo=bar", h)
#> normal curl response
```

```r
# after mocking turned on
enable("curl")
# fails with webmockr message
curl_fetch_memory("https://httpbin.org/get?foo=bar", h) 
#> Error: Real HTTP connections are disabled.
#> Unregistered request:
#>   GET:  https://httpbin.org/get?foo=bar   with headers {accept: */*, accept-encoding: gzip, deflate, host: localhost:9359, user-agent: R (3.5.2 x86_64-apple-darwin15.6.0 x86_64 darwin15.6.0)}
#> 
#> You can stub this request with the following snippet:
#> 
#>    stub_request('get', uri = 'https://httpbin.org/get?foo=bar') %>%
#>      wi_th(
#>        headers = list('accept' = '*/*', 'accept-encoding' = 'gzip, deflate', 'host' = 'localhost:9359', 'user-agent' = 'R (3.5.2 x86_64-apple-darwin15.6.0 x86_64 darwin15.6.0)')
#>      )
#> ============================================================
```

```r
# after stubbing request
stub_request("get", "https://httpbin.org/get?foo=bar")
#> <webmockr stub>
#>   method: get
#>   uri: https://httpbin.org/get?foo=bar
#>   with:
#>     query:
#>     body:
#>     request_headers:
#>   to_return:
#>     status:
#>     body:
#>     response_headers:
#>   should_timeout: FALSE
#>   should_raise: FALS
```

```r
# now you get a mocked response
curl_fetch_memory("https://httpbin.org/get?foo=bar", h)
#>  $url
#>  [1] "https://httpbin.org/get?foo=bar"
#>  
#>  $status_code
#>  [1] 200
#>  
#>  $type
#>  [1] NA
#>  
#>  $headers
#>  raw(0)
#>  
#>  $modified
#>  [1] NA
#>  
#>  $times
#>  numeric(0)
#>  
#>  $content
#>  raw(0)
```

--- 

other things:

- for `curl_fetch_disk` I need to work out handling disk operations in a general purpose way for any pacakge adapater (https://github.com/ropensci/webmockr/issues/57), then can work on mocking for `curl_fetch_disk`

### CODE REVIEW

**Comment by jeroen** [comment]
Note from call: consider conditioning the callback on a unique secret header.

**Comment by jeroen** [comment]
I'm curious, how does `webmockr::curl_mock_req` know what is inside the `handle`? How does it know what the mocked request is?

**Comment by jeroen** [comment]
If curl would provide a way to explicitly let the handle be mock-able e.g. `handle_allow_mock(h)` would that work, or is that impractical for how mocking is used?

**Comment by sckott** [comment]
> how does webmockr::curl_mock_req know what is inside the handle?

by running `curl::curl_echo` https://github.com/ropensci/webmockr/blob/adapter-curl/R/curl_mocking.R#L25

**Comment by sckott** [comment]
> If curl would provide a way to explicitly let the handle be mock-able ...

would make things easier for sure as wouldn't have to run `curl_echo`

**Comment by sckott** [comment]
closing for now - we talked and decided to not do this

**Pull request closed without merging**
