### PR TITLE
support list options

### PR DESCRIPTION
**Pull request by datawookie**
Hi @jeroen, can we merge these changes into `master`? Thanks, Andrew.

### CODE REVIEW

**Comment by jeroen** [comment]
I should add some tests for this.

**Comment by datawookie** [comment]
Please let me know if there's something specific I can help with. Thanks!

**Comment by datawookie** [comment]
Thanks for working on this issue, @jeroen.

**Comment by jeroen** [comment]
Does this work with gmail smtp? Can you give me an example how you authenticate?

**Comment by datawookie** [comment]
For sure. I've actually wrapped it up in a package: https://github.com/datawookie/emayili.

**Comment by datawookie** [comment]
Thanks! Just tested with `master` and it's :100:.

**Pull request merged**
