### PR TITLE
Allow setting headers in curl_upload()

### PR DESCRIPTION
**Pull request by yihui**
For example, this could be useful for setting the `Authorization` header when using some web APIs. Thanks!

### CODE REVIEW

**Comment by jeroen** [comment]
It is already possible to set headers by passing them as the [`httpheader`](https://curl.se/libcurl/c/CURLOPT_HTTPHEADER.html) option like so:


```r
curl_upload(..., httpheader = c("Authorization: blabla")
```

**Comment by yihui** [comment]
Oh I wasn't aware of that. Thanks for the tip!

**Comment by yihui** [comment]
Not sure why, but this doesn't work in my case. It seems that the effects of `handle_setopt(httpheader)` and `handle_setheaders()` are different. Only the latter works.

**Comment by jeroen** [comment]
Are you using the correct format? Note that when setting the option you need to use a single string `"name: value"` and when using `handle_setheaders` you use `handle_setheaders(name = "value")`

**Comment by yihui** [comment]
Yes, I'm aware of the different formats. When I tested https://httpbin.org/headers, the `Authorization` headers are the same with both methods, but it just won't work for the web service that I intend to use. Let me see if I can make a minimal reprex.

**Comment by yihui** [comment]
Ahh. Figured it out. It took me a couple of hours to realize that I accidentally turned on my Chinese input method and typed the colon in Chinese (i.e., the full-width `：` instead of `: `). Since the whole thing `"name: value"` is a single string, it was hard to recognize it. That's why `handle_setheaders(name = "value")` worked. Is "Colon as a Service" a thing? That's an unexpected advantage of using `handle_setheaders()`.

**Comment by jeroen** [comment]
Glad you figured it out (and that I am blessed with speaking an ascii native language).

**Pull request closed without merging**
