### PR TITLE
Add multi_fdset() to return libcurl's FDs

### LINKED ISSUE #109: Extra file descriptors for polling
This is just an idea. It would be cool to be able to poll not just for the libcurl downloads, but other file descriptors as well. I could use this to poll for I/O from processes for example. `curl_multi_wait` supports this already, via the `extra_fds` and `extra_nfds` arguments. 

Unfortunately this will not work on the R connection level, since we cannot get the fds of the connections, but this might also be a good thing, considering the current half-supported status of custom connections.

But we could just pass in file descriptors in an integer vector.

### PR DESCRIPTION
**Pull request by gaborcsardi**
It also returns the suggested (max) timeout of libcurl.
This function is handy if the application needs to
poll for output from multiple sources, including libcurl
connections.

It fixes #109.

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks! I'll take your word on it that this is useful :)

**Comment by gaborcsardi** [comment]
Thanks for the quick merge! Yes, it will be tremendously useful. I still need to implement the joint polling of processes and libcurl FDs, though.

**Comment by jeroen** [comment]
How do I test this? I tried using the example in `?multi` however `curl_multi_fdset` only returns empty vectors.

**Comment by jeroen** [comment]
I have removed the header because it is unavailable on Windows and does not seem to be needed.

**Comment by gaborcsardi** [comment]
```r
{
  pool <- new_pool()
  for (i in 1:3) {  
    h1 <- new_handle(url = "https://eu.httpbin.org/delay/10")
    h2 <- new_handle(url = "https://httpbin.org/delay/5")
    multi_add(h1, done = force, fail = force, pool = pool)
    multi_add(h2, done = force, fail = force, pool = pool)
    multi_run(timeout = 1, pool = pool)
  }
  print(multi_fdset(pool = pool))
}
```

```
#> $reads
#> [1] 17 18 19 20 21
#> 
#> $writes
#> integer(0)
#> 
#> $exceptions
#> integer(0)
#> 
#> $timeout
#> [1] 1000
```

I am not sure what a good unit test would look like, though.

**Comment by gaborcsardi** [comment]
Sorry about the header, I forgot to say, that I only tested it on macos.....

**Comment by jeroen** [comment]
Your example makes me think you have an off by one error because it always returns one less file descriptor than the number of connections. Fixed @ https://github.com/jeroen/curl/commit/88e7f44e9998e9efba3b79fa2cd0ebcb45be6a6f

**Comment by gaborcsardi** [comment]
Right!

**Comment by gaborcsardi** [comment]
Right. Then a simpler example is 
```r
pool <- new_pool()
h1 <- new_handle(url = "https://eu.httpbin.org/delay/10")
h2 <- new_handle(url = "https://httpbin.org/delay/5")
multi_add(h1, done = force, fail = force, pool = pool)
multi_add(h2, done = force, fail = force, pool = pool)
multi_run(timeout = 1, pool = pool)
print(multi_fdset(pool = pool))
lapply(multi_list(pool), multi_cancel)
```

**Comment by jeroen** [comment]
This is one test to verify that `host_con` works:

```
pool <- new_pool(host_con = 7)
for (i in 1:10) {  
  h1 <- new_handle(url = paste0("https://eu.httpbin.org/delay/", i))
  multi_add(h1, done = force, fail = cat, pool = pool)
}
repeat{
res <- multi_run(pool = pool, poll = 1)
print(multi_fdset(pool = pool))
if(!res$pending)
  break
}
```

**Pull request merged**
