### PR TITLE
Don't wait for data in non-blocking curl() open()

### PR DESCRIPTION
**Pull request by gaborcsardi**
This is on top of #85 

It does not seem to cause any problems to me, but I admit that I haven't tested it thoroughly. But I really like this feature, so if you think that it has a chance of making it into curl, I'll be happy to add a bunch of tests.

### EDIT: some test cases:

```r

## Delayed data

library(curl)
con <- curl("http://httpbin.org/delay/10")
open(con, blocking = FALSE)
readLines(con)

while (isIncomplete(con)) {
  Sys.sleep(0.1)
  readLines(con)
}

## Error code, unauthorized

library(curl)
con <- curl("http://httpbin.org/status/401")
open(con, blocking = FALSE)
readLines(con)

while (isIncomplete(con)) {
  Sys.sleep(0.1)
  readLines(con)
}

## Error, DNS failed

con <- curl("http://this.is.invalid")
open(con, blocking = FALSE)
readLines(con)

while (isIncomplete(con)) {
  Sys.sleep(0.1)
  readLines(con)
}

## Error, no such host, will timeout

con <- curl("http://240.0.0.1")
open(con, blocking = FALSE)
readLines(con)

while (isIncomplete(con)) {
  Sys.sleep(0.1)
  readLines(con)
}

## No HTTP on that port

con <- curl("http://8.8.8.8:666")
open(con, blocking = FALSE)
readLines(con)

while (isIncomplete(con)) {
  Sys.sleep(0.1)
  readLines(con)
}
```

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Hmmm, error handling is not right with this, because reads can also fill in the status, not just open....

**Comment by gaborcsardi** [comment]
OK, better now.

**Comment by jeroen** [comment]
This has been open for too long, sorry :)

I want to accomodate your use case, but I would like the default interpretation of `blocking = FALSE` to stay the same as for socketConnections and other base connections. This means that the `blocking` attribute of a connection only refers to read/write. Opening should fail immediately, not some time later during a read.

Here is what I propose: we make the fully non-blocking behavior you suggest in this PR opt-in, by reserving a new character in the `open` parameter for `curl` or `open()`. So you can do:

```r
con <- url("https://httpbin.org/get")
open(con, "rbn", blocking = FALSE)
```

The `n` here will result in non-blocking `open()`, and `blocking` still refers to read.

Would that be OK or is that a terrible idea?

**Comment by jeroen** [comment]
Superseded by https://github.com/jeroen/curl/pull/95

**Pull request closed without merging**
