### PR TITLE
Fix #329: make rcurl_read() return without waiting if non-blocking

### LINKED ISSUE #329: Can't get all bytes received before RST
When a download is interrupted due to the server sending a TCP RST (Reset) packet, the last bytes received before the RST packet are stored in buffers in the curl package's C code, but can't be accessed by the R application. This is the case even if the R application uses `curl_fetch_stream` or `blocking=FALSE`.

Example R script:
```
library(curl)

args <- commandArgs(trailingOnly=TRUE)
url <- args[[1]]
dest <- args[[2]]

con <- file(dest, "wt", encoding="UTF-8")
tryCatch(
  {
    curl::curl_fetch_stream(
      url,
      fun=function(bytes) {cat(intToUtf8(bytes), file=con)}
    )
  },
  error=function(err) {
    cat("[Error: ", as.character(err), "]")
  },
  finally={
    close(con)
  }
)
```

When the server's output ends with a RST packet, the file created by this R script doesn't contain all of the data that the server claims to have sent before the RST packet; in the attached test case, it is missing 701 bytes from the end of the data. By contrast, a similar script using Python's "[requests](https://requests.readthedocs.io/en/latest/)" library is able to retrieve _nearly_ all of the expected data, and the `curl` command-line program gets all of it.

The [attached test](https://github.com/jeroen/curl/files/14053264/r-curl-rst-problem.tgz) reproduces the problem, using a Docker container to run an HTTP server that generates a RST packet at a desired location in the middle of a download (using the [scapy](https://scapy.readthedocs.io/en/latest/) Python library). The data processed through the R curl client is 701 bytes smaller than the data produced by the `curl` command-line tool (the difference increases as you increase the file size), as shown in the beginning of the test output:

```
url: http://reset-server:8800?bytes=200000&chunk_size=2001&packet_size=11000&reset=190000
#### Fetched curl output to curl.out ####
#### Fetched python output to py.out ####
#### Fetched R output to r.out ####
#### File sizes ####
196608 r.out
197298 py.out
197309 curl.out

#### Comparing r.out <-> curl.out ####
cmp: EOF on r.out after byte 196608, in line 10386
#### r.out (196608b) is 701 bytes smaller than curl.out (197309b) ####
```

### PR DESCRIPTION
**Pull request by rls-p4**
Fix #329: in the streaming or non-blocking case, have `rcurl_read()` return any buffered bytes immediately before attempting to fetch more from the remote server. This way, even if the subsequent fetch fails due to the server closing the connection, the application has access to the bytes already sent by the server and buffered inside the R client's C code.

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks. Can you add a 1 sentence summary to the NEWS file? You may ignore random CI failures.

**Comment by rls-p4** [comment]
Thanks @jeroen, it looks like 5.2.0 is already tagged and released, so should I start a new version 5.2.1 and put the summary in a new NEWS section for that?

**Comment by jeroen** [comment]
Yes that is ok

**Comment by rls-p4** [comment]
Great, thanks!

**Comment by jeroen** [comment]
This has landed on CRAN in curl 5.2.1.

**Pull request merged**
