### PR TITLE
trimws replacement, for R < 3.2.0

### LINKED ISSUE #138: R 3.1.x does not have `trimws`
So, either you need to depend on at least `3.2.0`, or (highly preferable for me) provide an alternative `trimws` implementation in `curl` itself. Something like:

```r
trimws <- function(x) {
  sub("\\s$", "", sub("^\\s+", "", x))
}
```

would do for `curl` I think. It is actually better than the base R implementation, because it handles all whitespace characters. Do you want this as a PR?

### PR DESCRIPTION
**Pull request by gaborcsardi**
Closes #138

### CODE REVIEW

**Comment by gaborcsardi** [comment]
@jeroen can you pls take a look at this? It is not urgent, but it would be great to include it in the next curl release.

Relatedly, are you interested in a PR that tests curl with R 3.1.x up to R-devel on Travis?

**Comment by jeroen** [comment]
Thanks for the reminder. Sure if you need 3.1 support.

**Comment by jeroen** [comment]
I'll probably need to do a release of curl soon because one of the unit tests is broken. Would you like to get anything in there to fix R 3.1?

**Comment by gaborcsardi** [comment]
There is actually one more thing, getting the curl fds doesn't work on Windows. (Which is my bad.) I'll fix it this weekend.

**Comment by jeroen** [comment]
You mean `curl_multi_fd()`? What is not working about it?

**Comment by gaborcsardi** [comment]
oops, forgot this, sorry. 

yeah, I forgot the details but a windows fd_set is different, and afair `curl_multi_fd` does not work on windows.

**Comment by jeroen** [comment]
I'll open a separate issue for this.

**Comment by jeroen** [comment]
This is on CRAN now.

**Comment by gaborcsardi** [comment]
Thanks, great!

**Pull request merged**
