### PR TITLE
Added domain to timeout message

### LINKED ISSUE #190: Add URL to timeout error message
Hi,
curl usually works great and we all completely rely on it.  Today I hit a rare problem that I tweeted about ([here](https://twitter.com/MattDowle/status/1153411113838469120)) in case someone else knows what the URL is that it is timing out on in this case.  In general, it would be great if the error message including the URL that it was timing out on. For cases like this where all I see is a log file.
image
I'm trying to create a PR to curl to do this. I searched this repo for the string "timed" to find the error message but nothing came up. Then I searched this repo for "curl_fetch_memory" and I found lots of usage but, oddly, not where it is defined. I'll keep trying.
Could you give me some hints as to where I might modify the code to include the URL in the timeout error message?
Thanks, Matt

### PR DESCRIPTION
**Pull request by mattdowle**
Closes #190 
Before this PR I could reproduce the timeout as follows : 
```R
> url <- "http://www.r-project.org"
> require(curl)
Loading required package: curl
> h <- new_handle()
> handle_setopt(h, connecttimeout_ms = 1L)
> curl_fetch_memory(url, h)
Error in curl_fetch_memory(url, h) : 
  Timeout was reached: Connection timed out after 1 milliseconds
```
with this PR, the new behavior is:
```R
> curl_fetch_memory(url, h)
Error in curl_fetch_memory(url, h) : 
  Timeout was reached: Connection timed out after 1 milliseconds: http://www.r-project.org/
```
Thanks to @krlmlr for the tip in the issue as to where to make this change.

### CODE REVIEW

**Comment by jeroen** [comment]
One problem is that URLs can be very long resulting in too large error messages. Also they may contain sensitive information such as tokens in the parameters, which should not be printed to the log files.

I think if we would do this, we should only print the domain part, not the full URL.

**Comment by gaborcsardi** [comment]
Another approach would be to create a unique id for the request, and include that in the error object.

**Comment by mattdowle** [comment]
Including only the domain part sounds good to me. I noticed that curl itself includes the domain in the error message in other circumstances (I'll reproduce and paste the output here.)
I'll work on a way to do that (hopefully there's a library function that can extract the domain part) and submit ...

**Comment by mattdowle** [comment]
This is pretty tough.  I tried [this approach](https://daniel.haxx.se/blog/2018/09/09/libcurl-gets-a-url-api/) first but it looks like that URL api is relatively recent in curl (7.62.0) and I only had 7.58.0 on my Ubuntu 18.04.  I kept that attempt in commit 3 for reference.
So I went for a strchr approach to extract the hostname and port from the standard URL returned by CURLINFO_EFFECTIVE_URL.
With the latest commit, here's the output.
```
> require(curl)
Loading required package: curl
> url = "www.google.com:81"
> h <- new_handle()
> curl_fetch_memory(url, h)
Error in curl_fetch_memory(url, h) :+1: 
  Timeout was reached: Connection timed out after 10004 milliseconds: www.google.com:81
> handle_setopt(h, connecttimeout = 1)
> curl_fetch_memory(url, h)
Error in curl_fetch_memory(url, h) :+1: 
  Failed to connect to www.google.com port 81: Connection timed out
# curl's own message when CURLE_COULDNT_CONNECT includes the hostname
```

**Comment by mattdowle** [comment]
@jeroen I made the domain extraction more robust: a restricted set of schemes and if anything is not correct it falls back to the previous message without the domain. Also added lots of comments. What you think? I'm happy to make further changes as you suggest.

**Comment by mattdowle** [comment]
1 out of the 10 travis builds has failed twice. I don't think it's to do with this PR.
```
No output has been received in the last 10m0s, this potentially indicates a stalled
build or something wrong with the build itself.
Check the details on how to adjust your build configuration on:
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by jeroen** [comment]
Ended up implementing a somewhat simpler url parser. I still feel a bit uncomfortable manually parsing URLS; hopefully I didn't overlook any URL edge cases.

**Pull request closed without merging**
